//! The test inventory `checks_green` provides and `tests_not_deleted`
//! consumes.
//!
//! ## Why this exists
//!
//! `tests_not_deleted` reads the *source*. That is a weaker claim than
//! "the test still runs", and the gap is not academic. The static reading
//! cannot see:
//!
//! - a test generated by a macro, which has no `#[test]` attribute in the
//!   source at all;
//! - a test that a `#[cfg]` has compiled out on this platform or feature set;
//! - a test that the harness has skipped for a reason the source does not say.
//!
//! `cargo test -- --list` is the real inventory: the names as the compiler
//! sees them, for the configuration actually being built. It is what a
//! supervisor should be comparing, because "the test file still has a
//! `#[test]`" is not the same statement as "the test runs".
//!
//! ## What it does not fix
//!
//! The inventory is a *head* snapshot. It cannot answer "was a test removed
//! between the base commit and now" on its own, because the base tree would
//! have to be built and listed too — which is a second full compile, on every
//! commit, to answer a question the source reading already answers correctly.
//! So the two are **combined, not substituted**:
//!
//! - the **source reading** answers *removal*, across the two trees, cheaply;
//! - the **inventory** answers *is it actually running*, at the head, exactly.
//!
//! The gate reports a source-only test the inventory does not contain. That
//! is a real finding — a test nobody runs is a test that was silently deleted
//! in everything but name — and it is the class of thing a static reading
//! cannot see at all.
//!
//! ## The provided data
//!
//! Cargo's `--list` output is one `<name>: test` per line. The shape varies by
//! origin and the difference matters:
//!
//! ```text
//! approvals::tests::test_approval_lifecycle: test   <- unit test, module path
//! test_macos_keychain_crud_lifecycle: test           <- integration test, bare
//! src/lib.rs - add (line 42): test                   <- doc test, file + line
//! ```
//!
//! All three are recorded, with the kind preserved, because a doc test has no
//! counterpart in the source tree at all and must not be compared against one.

use std::collections::BTreeSet;

/// Where a test came from, which determines whether it can be compared with a
/// source reading at all.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum TestKind {
    /// A `#[test]` or `#[tokio::test]`, named by its module path.
    Unit,
    /// A test in an integration test binary, named without a module path.
    Integration,
    /// A doc test, named by file and line. Has no source-tree counterpart.
    Doc,
}

/// One test the compiler says it will run.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub struct InventoryTest {
    /// The name exactly as cargo printed it.
    pub name: String,
    /// Where it came from, which decides whether it can be compared with a
    /// source reading at all.
    pub kind: TestKind,
}

impl InventoryTest {
    /// The name to match a source-tree test against.
    ///
    /// `None` for a doc test: `src/lib.rs - add (line 42)` names a snippet
    /// inside a file, not a function, and pretending it corresponds to a
    /// `#[test]` in the source would invent a relationship.
    pub fn comparable_name(&self) -> Option<String> {
        match self.kind {
            TestKind::Doc => None,
            TestKind::Unit | TestKind::Integration => Some(self.name.clone()),
        }
    }
}

/// The set of tests a build will actually run.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct TestInventory {
    tests: Vec<InventoryTest>,
}

impl TestInventory {
    /// An empty inventory. A build with no tests is a real state, and
    /// conflating it with "we could not find out" is the error this type
    /// exists to prevent.
    pub fn empty() -> Self {
        Self::default()
    }

    /// Parse `cargo test -- --list` output.
    ///
    /// # Errors
    ///
    /// `true`-returning helper rather than a `Result` on purpose: unparseable
    /// lines are skipped and counted, and the caller decides what a partial
    /// inventory means. Silently dropping them and calling the result
    /// "complete" is the failure this avoids.
    pub fn parse(listing: &str) -> (Self, usize) {
        let mut tests = Vec::new();
        let mut skipped = 0usize;
        for line in listing.lines() {
            let line = line.trim();
            if line.is_empty() {
                continue;
            }
            // Doc tests print as `src/lib.rs - add (line 42): test` — they
            // *also* end in `: test`, so they have to be recognised **before**
            // the general shape or every doc test is filed as a unit test.
            // Checking the general shape first was a real bug the fixture
            // caught: it reported a doc test as comparable, which would let it
            // mask a genuinely missing unit test.
            if line.contains(".rs - ") {
                tests.push(InventoryTest {
                    name: line.to_string(),
                    kind: TestKind::Doc,
                });
                continue;
            }
            if let Some(name) = line.strip_suffix(": test") {
                let name = name.trim();
                if name.is_empty() {
                    skipped += 1;
                    continue;
                }
                let kind = if name.contains("::") {
                    TestKind::Unit
                } else {
                    TestKind::Integration
                };
                tests.push(InventoryTest {
                    name: name.to_string(),
                    kind,
                });
                continue;
            }
            if line.starts_with("Doc-tests") {
                tests.push(InventoryTest {
                    name: line.to_string(),
                    kind: TestKind::Doc,
                });
                continue;
            }
            // Progress lines, blank separators, and anything else. Counted so a
            // caller can tell a complete inventory from a partial one.
            skipped += 1;
        }
        tests.sort();
        tests.dedup();
        (Self { tests }, skipped)
    }

    /// Every test.
    pub fn tests(&self) -> &[InventoryTest] {
        &self.tests
    }

    /// How many tests.
    pub fn len(&self) -> usize {
        self.tests.len()
    }

    /// Whether the build declared no tests at all.
    pub fn is_empty(&self) -> bool {
        self.tests.is_empty()
    }

    /// The names this inventory can be matched against, as owned strings.
    ///
    /// Owned because a doc test is excluded here but a `BTreeSet<&str>`
    /// borrowing from a temporary `String` would not survive the statement.
    pub fn comparable_names(&self) -> BTreeSet<String> {
        self.tests
            .iter()
            .filter_map(|t| t.comparable_name())
            .collect()
    }

    /// Whether a source-tree test of this name is in the inventory.
    ///
    /// Both the bare name and the module path are accepted, because cargo
    /// prints integration tests bare and unit tests with a path, and a source
    /// reading knows the module but not which binary the test ended up in.
    /// The bare name is the case that matters: `tests/foo.rs` declares
    /// `fn works()`, and cargo prints `works`.
    pub fn contains(&self, name: &str) -> bool {
        let bare = name.rsplit("::").next().unwrap_or(name);
        self.tests.iter().any(|t| match t.kind {
            // A doc test is a snippet, not a function, and must never stand in
            // for a real test.
            TestKind::Doc => false,
            TestKind::Unit | TestKind::Integration => t.name == name || t.name == bare,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const LISTING: &str = "\
approvals::tests::test_approval_lifecycle: test
mcp::tests::search_parameters_deserialize: test
test_macos_keychain_crud_lifecycle: test
src/lib.rs - add (line 42): test
";

    #[test]
    fn the_three_shapes_are_distinguished() {
        let (inv, _) = TestInventory::parse(LISTING);
        assert_eq!(inv.len(), 4);
        let kinds: Vec<TestKind> = inv.tests().iter().map(|t| t.kind).collect();
        assert!(kinds.contains(&TestKind::Unit));
        assert!(kinds.contains(&TestKind::Integration));
        assert!(kinds.contains(&TestKind::Doc));
    }

    #[test]
    fn a_unit_test_matches_by_its_module_path() {
        let (inv, _) = TestInventory::parse(LISTING);
        assert!(inv.contains("approvals::tests::test_approval_lifecycle"));
    }

    #[test]
    fn an_integration_test_matches_by_its_bare_name() {
        // The case that matters: a source reading knows the module path, and
        // cargo prints integration tests with none.
        let (inv, _) = TestInventory::parse(LISTING);
        assert!(inv.contains("test_macos_keychain_crud_lifecycle"));
    }

    #[test]
    fn a_source_test_whose_module_cargo_omits_still_matches() {
        let listing = "works: test\n";
        let (inv, _) = TestInventory::parse(listing);
        // Read from `tests/foo.rs` as `works`, and from `mod a` as `a::works`.
        assert!(inv.contains("works"));
        assert!(inv.contains("a::works"));
    }

    #[test]
    fn a_doc_test_is_never_matched_against_a_source_test() {
        // `src/lib.rs - add (line 42)` is a snippet, not a function. Treating
        // it as one would let a doc test mask a real missing unit test.
        let (inv, _) = TestInventory::parse(LISTING);
        assert!(!inv.contains("add (line 42)"));
        assert!(!inv.contains("src/lib.rs - add (line 42)"));
        assert!(!inv.comparable_names().contains("add (line 42)"));
        assert!(!inv.comparable_names().iter().any(|n| n.contains("add")));
    }

    #[test]
    fn a_test_that_is_not_in_the_inventory_is_reported_as_missing() {
        // The finding this integration exists for: a test still in the source
        // that the build does not run.
        let (inv, _) = TestInventory::parse(LISTING);
        assert!(!inv.contains("tests::silently_skipped"));
    }

    #[test]
    fn unparseable_lines_are_counted_rather_than_silently_dropped() {
        // A partial inventory must be distinguishable from a complete one.
        let (inv, skipped) = TestInventory::parse("running 0 tests\n\nsome noise\n: test\n");
        assert_eq!(inv.len(), 0, "`: test` with no name is not a test");
        assert_eq!(skipped, 3);
    }

    #[test]
    fn an_empty_listing_is_an_empty_inventory_not_a_failure() {
        let (inv, _) = TestInventory::parse("");
        assert!(inv.is_empty());
    }

    #[test]
    fn parsing_is_deterministic() {
        let a = TestInventory::parse(LISTING).0;
        let b = TestInventory::parse(LISTING).0;
        assert_eq!(a, b);
        // And order-independent, since cargo's output order is not guaranteed.
        let reversed: String = LISTING.lines().rev().collect::<Vec<_>>().join("\n");
        assert_eq!(a, TestInventory::parse(&reversed).0);
    }
}
